export const api = "http://localhost:5000";

// const postsData = [
//   {
//     id: 1,
//     title: "Post 1",
//     photos: [],
//     seatCapacity: 5,
//     price: 5000,
//     type: "male",
//     availabe: true,
//     contact: "01725566253",
//     details: "CUET Gate er pashe",
//     location: "CUET Main gate",
//     coordinates: "99990.5566",
//   },
//   {
//     id: 1,
//     title: "Post 1",
//     photos: [],
//     seatCapacity: 5,
//     price: 5000,
//     type: "male",
//     availabe: true,
//     contact: "01725566253",
//     details: "CUET Gate er pashe",
//     location: "CUET Main gate",
//     coordinates: "99990.5566",
//   },
//   {
//     id: 1,
//     title: "Post 1",
//     photos: [],
//     seatCapacity: 5,
//     price: 5000,
//     type: "male",
//     availabe: true,
//     contact: "01725566253",
//     details: "CUET Gate er pashe",
//     location: "CUET Main gate",
//     coordinates: "99990.5566",
//   },
//   {
//     id: 1,
//     title: "Post 1",
//     photos: [],
//     seatCapacity: 5,
//     price: 5000,
//     type: "male",
//     availabe: true,
//     contact: "01725566253",
//     details: "CUET Gate er pashe",
//     location: "CUET Main gate",
//     coordinates: "99990.5566",
//   },
//   {
//     id: 1,
//     title: "Post 1",
//     photos: [],
//     seatCapacity: 5,
//     price: 5000,
//     type: "male",
//     availabe: true,
//     contact: "01725566253",
//     details: "CUET Gate er pashe",
//     location: "CUET Main gate",
//     coordinates: "99990.5566",
//   },
//   {
//     id: 2,
//     title: "Post 2",
//     photos: [],
//     seatCapacity: 5,
//     price: 5000,
//     type: "male",
//     availabe: true,
//     contact: "01725566253",
//     details: "CUET Gate er pashe",
//     location: "CUET Main gate",
//     coordinates: "99990.5566",
//   },
//   // Add more posts as needed
// ];
